error in close event may be missing
Stacktrace

TypeError: Cannot read property 'message' of undefined
  at IncomingMessage.<anonymous> (/descript2/lib/de.request.js:199:36)
  at IncomingMessage.emit (events.js:194:15)
  at Socket.socketCloseListener (_http_client.js:356:11)
  at Socket.emit (events.js:194:15)
  at TCP._handle.close (net.js:600:12)